### ISSUE TITLE
No package 'cryptoauth-0.2' found during installation on Debian

### ISSUE THREAD

**Issue by julisch94** [cryptotronix/EClet#18]
Unfortunately, I keep getting an error about a missing package `cryptoauth-0.2` during install:
```
configure: error: Package requirements (cryptoauth-0.2) were not met:

No package 'cryptoauth-0.2' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables DEPS_CFLAGS
and DEPS_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

My problem can be reconstructed by the following commands:
```
docker run -it --rm debian:buster-slim
$> apt update
$> apt install -y wget
$> wget https://github.com/cryptotronix/EClet/releases/download/0.1.1/eclet-0.1.1.tar.gz
$> tar -xzvf eclet-0.1.1.tar.gz
$> apt install -y build-essential autotools-dev automake autoconf libtool libxml2-dev check texinfo libgcrypt20-dev
$> apt install -y pkg-config
$> cd eclet-0.1.1
$> ./autogen.sh
```

The shell then starts to run until it stops with the aforementioned error message. Unfortunately, I'm not able to locate the package cryptoauth-0.2.

How am I supposed to install the missing package?
Could somebody please help me install this package?

**Comment by 1smawell** [comment]
Hi julisch, i have the same problem, im using a BeagleBone Black with a cryptocape and i can't install eclet,

Did you have a solution for this issue?

**Comment by julisch94** [comment]
Unfortunately not.

**Comment by MoonCactus** [comment]
One+ year later, same issue, looks like this library just vanished from the web. Is there a chance you located it somewhere since ? Did you move to  another crypto chip ?

**Comment by MoonCactus** [comment]
I solved it! Get the library directlt at Microchip, e.g.
    https://github.com/cryptotronix/libcrypti2c/releases (I used 0.4.0)
Then just `./configure && make && make install` the lib.

cc  @julisch94  & @1smawell 
I think the issue should be closed (and may be a line added in the REAME...)
