### ISSUE TITLE
Investigate storing public key on ECC108

### ISSUE THREAD

**Issue by jbdatko** [cryptotronix/EClet#8]
Investigate / implement the option to store a public key on the ECC108. This would allow for verification of signatures where the public key stays on the device. Consider an option to store the public key on the device or in a ~/.eclet file.

Suggested by karl_34 on IRC.

**Comment by jbdatko** [comment]
This feature is not a public feature.

**Comment by hvisage** [comment]
When you say "public feature", does that mean it's not available from the documentation, or not available to the public users of this device?

**Comment by jbdatko** [comment]
Public as in it's not obvious how to do it without reading the NDA datasheet. Atmel released an API and with their ACES tool, it's pretty obvious how to perform signing and verification of an externally provided key. Last I checked, how to perform a signature verification of an internally stored key is not disclosed in that API. I'll have to take another look, but if that is indeed the case... I'm not sure I can really make that software available.

It's a bit frustrating, NDAs and what not. Atmel releases more publically available than most manufacturers, which is very nice. But there are some useful features, like this one, that it would be great to have, but the public-ness of them is uncertain.

**Comment by hvisage** [comment]
(nod)
Will need to reread my NDA to see about opensource software, though my needs aren't yet opensource (or even remotely usable outside my system at present)
